name: Test Windows
on:
  push: {}
  workflow_dispatch: {}

jobs:
  unit-test:
    name: Unit Test Windows
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Verify PHP
        run: php --version

      - name: Install dependencies
        run: composer install

      - name: Test
        run: php ./vendor/phpunit/phpunit/phpunit --configuration ./phpunit.xml --testsuite Unit
